// types.js
const UPDATE_CELL = "UPDATE_CELL";
const NEW_BOARD = "NEW_BOARD";
const RESET_BOARD = "RESET_BOARD";
const BACKTRACK_BOARD = "BACKTRACK_BOARD";
const SOLVE_INSTANTLY = "SOLVE_INSTANTLY";
const VALIDATE_SOLUTION = "VALIDATE_SOLUTION";
const UNDO_MOVE = "UNDO_MOVE";
const BACKTRACK_SPEED = "BACKTRACK_SPEED";
const LEVELS_CHANGE = "LEVELS_CHANGE";
const USER_PERFORMANCE = "USER_PERFORMANCE";

export default {
  UPDATE_CELL,
  NEW_BOARD,
  RESET_BOARD,
  BACKTRACK_BOARD,
  SOLVE_INSTANTLY,
  VALIDATE_SOLUTION,
  UNDO_MOVE,
  BACKTRACK_SPEED,
  LEVELS_CHANGE,
  USER_PERFORMANCE,
};
